### PR TITLE
Retest for #60

### PR DESCRIPTION
**Pull request by JanSchankin**
I've added some further tests with some addional fixes for #60 as discussed.

I've also reduced the number of public conversion methods in PersistentBeanFactory and changed some method names, hoping this would increase the readability. I'm looking foward to here your thoughts :-)

### CODE REVIEW

**Review by rcschrg — COMMENTED** [review]
I like it better than the original naming, but I think the scheme of/toBean(List/Array) without ifNecessary would be better, also it would make sense to separate the core logic and the extension/transformation check logic.

**Comment by JanSchankin** [comment]
It was unclear to me what a _Bean_ in `ofBean()` and `toBean()` is. It could be both, the `PersistentBean` or the _original_ Bean. Actually, I think this distinction could be clearer in several places. If you prefere the of/to schema, we could use `ofPersistentBean()` and `toPersistentBean()` to make this more clear. What do you think?

**Comment by rcschrg** [comment]
Hm, had another though, what about convert and revert? Then we should also rename factory to converter.

**Comment by JanSchankin** [comment]
I've pushed a new refactoring according to your suggestions.
I think, separation of  core logic and the extension/transformation check logic is a new issue, I think thats more refactoring and not related to #60, is it?

**Pull request merged**
